### ISSUE TITLE
Why mutual information I(x;x) is not equal to h(x)? 

### ISSUE THREAD

**Issue by qiongxiu** [gregversteeg/NPEET#16]
Hi, following your example,  I try to test whether the mutual information estimation makes sense or not.  But there is something wrong with mutual information esitmator, because it is very strange that I(x;x) and h(x) are not the same.
Do you have any idea of this?

x = [[1.3],[3.7],[5.1],[2.4],[3.4]]
y = [[1.5],[3.32],[5.3],[2.3],[3.3]]
ee.mi(x,x)
Out[182]: 0.36067376022224085

ee.entropy(x)
Out[183]: 2.706665509186988

ee.entropy(y)
Out[184]: 2.6794531992583743

ee.mi(y,y)
Out[185]: 0.36067376022224085

**Comment by gregversteeg** [comment]
For continuous random variables, the mutual information I(x,x) will not be the same as *differential entropy* (entropy defined for continuous variables). 
For continuous random variables, I(x,x) will generally be infinite. The reason is that continuous numbers like x=5.3857838474.... can have an infinite number of bits of precision, so a noiseless channel (from x to x) will have infinite mutual information. 
Differential entropy is different from Shannon entropy for discrete random variables in various ways. For instance, differential entropy can be negative.

**Comment by qiongxiu** [comment]
I see, I overlooked the infinite bits thing in practice,  thanks a lot, really helpful.
