### ISSUE TITLE
How to estimate MMI

### ISSUE THREAD

**Issue by aleksejs-fomins** [gregversteeg/NPEET#21]
Hi Greg,

I would like to compute [MMI](https://en.wikipedia.org/wiki/Multivariate_mutual_information) (aka [Interaction Information](https://en.wikipedia.org/wiki/Interaction_information)) for 3 variables. There are several ways to do this by combining entropies and mutual infromations, for example

I(X:Y:Z) = I(X:Y) - I(X:Y|Z)

or

I(X:Y:Z) = H(X) + H(Y) + H(Z) - H(XY) - H(XZ) - H(YZ) + H(XYZ)

* Is there a difference as to which formula to use?
* Are there some tricks to keep in mind to minimize effect of bias?
* I'm interested to determine if MMI is significant (shuffle test), but also to determine its sign to evaluate if MMI is more on the synergistic or the redundant side. If MMI turns out to be significantly different from zero from shuffle test, is it reasonable to conclude that it likely has the correct sign as well?

**Comment by gregversteeg** [comment]
I'd expect the first to be better.
1. There are fewer terms. Each term could introduce some bias.
2. From Kraskov, "Estimating mutual information", they talk about how estimators with different numbers of variables have systematically different bias. The second version mixes lots of estimators with different numbers of variables. 

To make the first version even better, I'd make the number of variables the same for both estimates. How? Introduce a variable Z' = shuffle(Z). Because Z' is shuffled, it has no relation to X and Y. Therefore I(X:Y|Z') = I(X:Y). This way you can write: 
I(X:Y:Z) = I(X:Y|Z') - I(X:Y|Z)
That way you can use the same estimator for both terms. I believe that this estimator should generally be unbiased, so that you can interpret the sign as likely to be correct.

**Comment by aleksejs-fomins** [comment]
Dear Greg,

Thanks a lot for your suggestions, they make a lot of sense. If possible, I have a follow-up question. I also want to calculate [total correlation](https://en.wikipedia.org/wiki/Total_correlation) in high-dimensional space (50 dimensions). I see that NPEET already implements `tc()` function. However, when I look at the implementation, I see that it computes the sum of individual 1D entropies, as well as the multivariate entropy, and then subtracts the two. While theoretically this is correct, it seems to go against the recommendations you have just given me. Indeed, I do get occasional negative values for the total correlation when I use it.

The question is - would it be better to use the total correlation definition based on KL-divergence? Based on your suggestion above, I would guess that we can shuffle each variable independently to destroy any relationship, and then compute KL-divergence between original and shuffled dataset. I can provide implementation for this method if you wish. I just want to make sure if what I am suggesting makes sense at all

**Comment by gregversteeg** [comment]
Yes, you're right, the way you proposed sounds like the best way to implement this. I'll happily merge it in if you want to submit it.

**Comment by aleksejs-fomins** [comment]
Dear Greg,

To the best of my understanding, the function should be as follows

```
def tc(x, k=3, base=2):
    xSh = np.copy(x)
    for iCol in range(xSh.shape[1]):
        np.random.shuffle(x[:, iCol])
        
    return kldiv(x, xSh, k, base)
```
At least for some basic examples the results seem to be sensible. It also seems slower than the original, but that is to be expected I guess.
