### ISSUE TITLE
Compute the Jensen–Shannon divergence

### ISSUE THREAD

**Issue by Duconnor** [gregversteeg/NPEET#23]
Hi there! Thank you for making and sharing such a useful package.

I've noticed that the estimation of Jensen-Shannon divergence is currently not supported in this package. Do you have any plan of adding it to this package in the future? If not, is there any workaround to make use of the current supported functions to compute the Jensen–Shannon divergence? Thanks a lot~

**Comment by gregversteeg** [comment]
There should be an easy way. You can write JSD in terms of KL divergence and then use the KL divergence estimators. 
```
p = [[1.3],[3.7],[5.1],[2.4],[3.4]]  # samples from p(x)
q = [[1.5],[3.32],[5.3],[2.3],[3.3]]  # samples from q(x)
JSD_p_q = 0.5 * (ee.kldiv(p, p+q) + ee.kldiv(q, p+q))  # JSD(p|q) 
```
Note that I'm using a little trick here where p+q concatenates lists for python. If you are using numpy arrays, you'll need to use np.concat. 

A second comment is that I'm not sure this simple approach is a good idea. The reason is that the samples appearing in p and some of the samples in p+q are identical... this may bias the estimator in unexpected ways. A better way would be to split p into two sets, p_a and p_b. for n points (randomly, or assuming they are already randomly arranged): 
```
p_a = p[:n/2]
p_b = p[n/2:]
q = ... # same for q
JSD_p_q = 0.5 * (ee.kldiv(p_a, p_b+q) + ee.kldiv(q_a, p+q_b))  # JSD(p|q) 
```
Finally, the more general formulation of JSD allows weighting of the distributions. I don't know off-hand if the non-parametric estimators can be adapted to weighted samples.
